backbone: 
    type: "resnet50"
head:
    type: "FDRHead"
        
fourier_converter:
    beta_train: 0.06
    beta_test : 0.008
    platform: "cv2" # platform to excute Fourier transform
                    # ["cv2", "torch"]

target_width : 224
target_height: 512
grid_width   : 9
grid_height  : 9

train: True 

        
